import type { Metadata } from "next";
import "./globals.css";
import { generalFont } from "@/config/fonts";
import TopMenu from "@/components/ui/top-menu/TopMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${generalFont.className} antialiased`}>
        <TopMenu />

        {children}
      </body>
    </html>
  );
}
