export const data = [
  {
    id: 1,
    username: "lazydog371",
    gender: "female",
    name: "Lori Russell",
    email: "lori.russell@example.com",
    phone: "(855) 748-5324",
    city: "Elgin",
    state: "Delaware",
    country: "United States",
    nat: "US",
    friends: [{ id: 2, name: "Ceyhan Koç"}, { id: 3, name: "Mia Jackson"}],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    id: 2,
    username: "redladybug989",
    gender: "female",
    name: "Ceyhan Koç",
    email: "ceyhan.koc@example.com",
    phone: "(260)-239-1979",
    city: "Ankara",
    state: "Ankara",
    country: "Turkey",
    nat: "TR",
    friends: [{ id: 1, name: "Lori Russell"}, { id: 3, name: "Mia Jackson"}],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    id: 3,
    username: "brownwolf725",
    gender: "female",
    name: "Mia Jackson",
    email: "mia.jackson@example.com",
    phone: "(390)-027-3768",
    city: "Auckland",
    state: "Auckland",
    country: "New Zealand",
    nat: "NZ",
    friends: [{ id: 1, name: "Lori Russell"}, { id: 2, name: "Ceyhan Koç"}],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    id: 4,
    username: "blackswan371",
    gender: "male",
    name: "Donzílio Martins",
    email: "donzilio.martins@example.com",
    phone: "(87) 1589-5496",
    city: "Rio de Janeiro",
    state: "Rio de Janeiro",
    country: "Brazil",
    nat: "BR",
    friends: [{ id: 5, name: "Ege Kaplangı"}, { id: 6, name: "Gail Graves"}],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    id: 5,
    username: "sadwolf352",
    gender: "female",
    name: "Ege Kaplangı",
    email: "ege.kaplangi@example.com",
    phone: "(264)-178-9302",
    city: "Istanbul",
    state: "Istanbul",
    country: "Turkey",
    nat: "TR",
    friends: [{ id: 4, name: "Donzílio Martins"}, { id: 6, name: "Gail Graves"}],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    id: 6,
    username: "orangepanda119",
    gender: "female",
    name: "Gail Graves",
    email: "gail.graves@example.com",
    phone: "(827) 226-2665",
    city: "Houston",
    state: "Texas",
    country: "United States",
    nat: "US",
    friends: [{ id: 4, name: "Donzílio Martins"}, { id: 5, name: "Ege Kaplangı"}],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    id: 7,
    username: "brownostrich601",
    gender: "female",
    name: "Zuzanna Horgen",
    email: "zuzanna.horgen@example.com",
    phone: "75390472",
    city: "Oslo",
    state: "Oslo",
    country: "Norway",
    nat: "NO",
    friends: [{ id: 8, name: "Predrag Jelačić"}, { id: 9, name: "Lyubanya Senko"}],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    id: 8,
    username: "heavyelephant196",
    gender: "male",
    name: "Predrag Jelačić",
    email: "predrag.jelacic@example.com",
    phone: "016-5332-498",
    city: "Belgrade",
    state: "Belgrade",
    country: "Serbia",
    nat: "RS",
    friends: [{ id: 7, name: "Zuzanna Horgen"}, { id: 9, name: "Lyubanya Senko"}],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    id: 9,
    username: "sadladybug764",
    gender: "female",
    name: "Lyubanya Senko",
    email: "lyubanya.senko@example.com",
    phone: "(096) P76-4968",
    city: "Kyiv",
    state: "Kyiv",
    country: "Ukraine",
    nat: "UA",
    friends: [{ id: 7, name: "Zuzanna Horgen"}, { id: 8, name: "Predrag Jelačić"}],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
  {
    id: 10,
    username: "sadladybug987",
    gender: "female",
    name: "Asya Akimenko",
    email: "asya.akimenko@example.com",
    phone: "7485",
    city: "Kharkiv",
    state: "Kharkiv",
    country: "Ukraine",
    nat: "UA",
    friends: [{ id: 8, name: "Predrag Jelačić"}, { id: 9, name: "Lyubanya Senko"}],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
  },
];
